apiVersion: v1
kind: Service
metadata:
  name: campibus-core-service
spec:
  selector:
    app: campibus-core
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: campibus-payments-service
spec:
  selector:
    app: campibus-payments
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: campibus-digital-wallet-service
spec:
  selector:
    app: campibus-digital-wallet
  ports:
  - port: 8082
    targetPort: 8082