apiVersion: apps/v1
kind: Deployment
metadata:
  name: campibus-digital-wallet
spec:
  selector:
    matchLabels:
      app: campibus-digital-wallet
  template:
    metadata:
      labels:
        app: campibus-digital-wallet
    spec:
      containers:
        - name: campibus-digital-wallet
          image: mathlimma/campibus-digital-wallet:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always