spring:
  thymeleaf:
    cache: false
  datasource:
    password: admin
    url: jdbc:h2:mem:db_campibus
    username: admin
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  servlet:
    context-path: /campibus/api/

