apiVersion: apps/v1
kind: Deployment
metadata:
  name: campibus-payments
spec:
  selector:
    matchLabels:
      app: campibus-payments
  template:
    metadata:
      labels:
        app: campibus-payments
    spec:
      containers:
        - name: campibus-core
          image: mathlimma/campibus-payments:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always