spring:
  datasource:
    password: admin
    url: jdbc:h2:mem:db_campibus_digital_wallet
    username: admin
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080
  servlet:
    context-path: /campibus-wallet
