apiVersion: v1
kind: Service
metadata:
  name: campibus-core-service
spec:
  selector:
    app: campibus-core
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ks-core-service
spec:
  selector:
    app: ks-core
  ports:
  - port: 8081
    targetPort: 8080