server:
  servlet:
    context-path: /campibus-core
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    password: admin
    url: jdbc:h2:mem:db_campibus_core
    username: admin
  h2:
    console:
      enabled: true
      path: /h2-console


