apiVersion: apps/v1
kind: Deployment
metadata:
  name: campibus-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: campibus-core
  template:
    metadata:
      labels:
        app: campibus-core
    spec:
      containers:
        - name: campibus-core
          image: mathlimma/campibus-core:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always